apiVersion: apps/v1
kind: Deployment
metadata:
  name: evershop-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evershop-app
  template:
    metadata:
      labels:
        app: evershop-app
    spec:
      containers:
        - name: evershop-app
          image: evershop/evershop:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: evershop-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: evershop-config
                  key: DB_PORT
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: evershop-secrets
                  key: DB_PASSWORD
            - name: DB_USER
              value: postgres
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: evershop-config
                  key: DB_NAME
          resources:
            requests:
              memory: "150Mi"
              cpu: "150m"
            limits:
              memory: "150Mi"
              cpu: "150m"
---
apiVersion: v1
kind: Service
metadata:
  name: evershop-service
spec:
  selector:
    app: evershop-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer