name: Node.js prod

on:
  push:

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    #needs: testing
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/apptest:v2
      
      # - name: Build docker imagedfiovgu
      #   run: |-
      #     docker build -t abdalluhm/mynodejs:latest .

      # - name: Publish docker image
      #   run: |-
      #     docker push abdalluhm/mynodejs:latest